version: '3.9'

services:
  budgetbaby:
    build: .
    container_name: budgetbaby
    ports:
      - "8080:8080"
    environment:
      - ENV_PATH=/app/secrets/env-file
    volumes:
      - ./secrets:/app/secrets
    restart: unless-stopped
    profiles:
      - prod

  budgetbaby-dev:
    build: .
    container_name: budgetbaby-dev
    ports:
      - "8080:8080"
    environment:
      - ENV_PATH=/app/secrets/env-file.docker-dev
    volumes:
      - ./secrets:/app/secrets
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles:
      - dev
